################################################## 
# Gotw_services.py 
# generated by ZSI.generate.wsdl2python
##################################################


from Gotw_services_types import *
import urlparse, types
from ZSI.TCcompound import ComplexType, Struct
from ZSI import client
import ZSI
from ZSI.generate.pyclass import pyclass_type

# Locator
class GotwLocator:
    GotwSoap_address = "http://gotw.nerc.ac.uk/facadeservice/gotw.asmx"
    def getGotwSoapAddress(self):
        return GotwLocator.GotwSoap_address
    def getGotwSoap(self, url=None, **kw):
        return GotwSoapSOAP(url or GotwLocator.GotwSoap_address, **kw)

# Methods
class GotwSoapSOAP:
    def __init__(self, url, **kw):
        kw.setdefault("readerclass", None)
        kw.setdefault("writerclass", None)
        # no resource properties
        self.binding = client.Binding(url=url, **kw)
        # no ws-addressing

    # op: <ZSI.wstools.WSDLTools.Message instance at 0x9647b8c>
    def GetGrantReferenceNumbers(self):

        request = GetGrantReferenceNumbersSoapIn()

        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://gotw.nerc.ac.uk/GetGrantReferenceNumbers", **kw)
        # no output wsaction
        response = self.binding.Receive(GetGrantReferenceNumbersSoapOut.typecode)
        GetGrantReferenceNumbersResult = response._GetGrantReferenceNumbersResult
        return GetGrantReferenceNumbersResult

    # op: <ZSI.wstools.WSDLTools.Message instance at 0x9647d0c>
    def GetGrantReferenceNumbersByDate(self, since):

        request = GetGrantReferenceNumbersByDateSoapIn()
        request._since = since

        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://gotw.nerc.ac.uk/GetGrantReferenceNumbersByDate", **kw)
        # no output wsaction
        response = self.binding.Receive(GetGrantReferenceNumbersByDateSoapOut.typecode)
        GetGrantReferenceNumbersByDateResult = response._GetGrantReferenceNumbersByDateResult
        return GetGrantReferenceNumbersByDateResult

    # op: <ZSI.wstools.WSDLTools.Message instance at 0x964fd2c>
    def GetDataByGrantReferenceNumber(self, refno):

        request = GetDataByGrantReferenceNumberSoapIn()
        request._refno = refno

        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://gotw.nerc.ac.uk/GetDataByGrantReferenceNumber", **kw)
        # no output wsaction
        response = self.binding.Receive(GetDataByGrantReferenceNumberSoapOut.typecode)
        GetDataByGrantReferenceNumberResult = response._GetDataByGrantReferenceNumberResult
        return GetDataByGrantReferenceNumberResult

GetGrantReferenceNumbersSoapIn = ns0.GetGrantReferenceNumbers_Dec().pyclass

GetGrantReferenceNumbersSoapOut = ns0.GetGrantReferenceNumbersResponse_Dec().pyclass

GetGrantReferenceNumbersByDateSoapIn = ns0.GetGrantReferenceNumbersByDate_Dec().pyclass

GetGrantReferenceNumbersByDateSoapOut = ns0.GetGrantReferenceNumbersByDateResponse_Dec().pyclass

GetDataByGrantReferenceNumberSoapIn = ns0.GetDataByGrantReferenceNumber_Dec().pyclass

GetDataByGrantReferenceNumberSoapOut = ns0.GetDataByGrantReferenceNumberResponse_Dec().pyclass
